apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-reservation-service
  namespace: backend-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-reservation-service
  template:
    metadata:
      labels:
        app: flight-reservation-service
    spec:
      containers:
        -env:
          - name: SPRING_ACTIVE_PROFILES
            value: 'local, mysql'

